# Site settings
title: Jekyll - Angular - Firebase (JAF)
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll
angular_version: 1.2.21


# Build settings
markdown: kramdown
permalink: pretty
